syntax_version: "2"
meta:
  labels:
  - "cleanthat"
  refs:
    branches:
    - "ref/heads/master"
    - "ref/heads/develop"
languages:
- language: "java"
  language_version: "11"
  processors:
  - engine: "revelc_imports"
    parameters:
      remove_unused: true
      groups: "java.,javax.,org.,com."
      static_groups: "java,*"
source_code:
  excludes:
  - "regex:.*/generated/.*"
  includes:
  - "regex:.*\\.java"
  encoding: "UTF-8"
  line_ending: "LF"
