spring:
  # https://stackoverflow.com/questions/10519265/jackson-overcoming-underscores-in-favor-of-camel-case
  jackson.property-naming-strategy: SNAKE_CASE

# https://stackoverflow.com/questions/38260725/add-prefix-to-all-spring-boot-actuator-endpoints
# Default is '/actuator'
management.endpoints.web.base-path: /api/actuator

sentry.dsn: https://22586844ad7d4f21b837cf5ea3600a1f@o222257.ingest.sentry.io/5245874

aws.lambda.invoke:
  access-key: XXX
  secret-key: YYY